#!/usr/bin/env python
import sys, os, time
import tweepy
keys = dict(
consumer_key='MzYeBPzBLuMgFSBaeg6qwCOsD',
consumer_secret='RRdrI94Hf9T9LFaQZezlSOLRgewRlR1tCPR9A0AWfpW1TRiE6S',
access_token='3422781745-5vKjG0BiPP6mjwkZ7RJpTTAMsenbxttua6WY8hR', 
access_token_secret='hOgwjkaNFyS7uXC2gICJ4xI48xVDQU3xNU9VcSCj6YVQW'
)

user = "@dubiousclot"

auth = tweepy.OAuthHandler(keys['MzYeBPzBLuMgFSBaeg6qwCOsD'], keys['RRdrI94Hf9T9LFaQZezlSOLRgewRlR1tCPR9A0AWfpW1TRiE6S'])
auth.set_access_token(keys['3422781745-5vKjG0BiPP6mjwkZ7RJpTTAMsenbxttua6WY8hR'], keys['hOgwjkaNFyS7uXC2gICJ4xI48xVDQU3xNU9VcSCj6YVQW'])
api = tweepy.API(auth)

def tweet():
	message=input("tweet: ")
	api.update_status(message)
	time.sleep(1000)
if __name__ == "__main__":
	while 1:
		tweet(ayo)               
